import { doc, getDoc, setDoc } from "firebase/firestore";
import { db } from "./config";

// ── Fish Audio TTS (Y Mizrachi voice) ──────────────────────────────────────
// Free tier: s2.1-pro-free. Returns raw MP3 bytes which we turn into a Blob URL.
//
// SECURITY: the Fish Audio API key is NEVER present in the frontend bundle.
// Voice is generated by the Cloudflare Worker route /api/generate-voice, which
// holds the key server-side (env var or Firestore config/fishAudioKey) and
// proxies to Fish Audio. On Android we additionally fall back to the native
// NextextNative.tts bridge (key compiled into the APK, not the JS bundle).

export const FISH_MODEL = "s2.1-pro-free";
export const Y_MIZRACHI_VOICE_ID = "9cc36d13d091468fa9c4cab838a6ecdf";

// Built-in Fish Audio voices. Admins can add more via the dashboard
// (stored as config/system.customVoices = [{ id, name, referenceId }]).
export const VOICE_PRESETS = [
  { id: "y-mizrachi", name: "Y Mizrachi", referenceId: "9cc36d13d091468fa9c4cab838a6ecdf" },
  { id: "rosh", name: "Rosh", referenceId: "afe83a515f954ba281f0631e8b414f56" },
  { id: "trump", name: "Trump", referenceId: "ee45da2963c047a6a07cd21fa3259ae0" },
  { id: "magnus", name: "Magnus", referenceId: "913b80e159c045bea5025943a44f7670" },
];

// All voices available to a user given the current system config (honours the
// admin "hide Rosh" switch, admin-hidden personas, and appends admin-created
// custom voices).
//
// When an admin hides a persona in the dashboard, its matching voice is also
// removed from the "Send Y Mizrachi Voice Note" / AI voice-reply pickers so the
// hidden persona can't be reached through the voice channel either.
const PERSONA_TO_VOICE = { mizrachi: "y-mizrachi", trump: "trump", magnusC: "magnus" };
export function getAvailableVoices(sysConfig) {
  const profiles = sysConfig?.voiceProfiles || {};
  const hidden = sysConfig?.hiddenPersonas || [];
  const hiddenVoiceIds = hidden.map((k) => PERSONA_TO_VOICE[k]).filter(Boolean);
  const presets = VOICE_PRESETS.filter(
    (v) => !(sysConfig?.hideRoshVoice === true && v.id === "rosh") && !hiddenVoiceIds.includes(v.id)
  );
  const custom = (sysConfig?.customVoices || [])
    .filter((v) => v && v.name && v.referenceId && !hiddenVoiceIds.includes(v.id || v.referenceId))
    .map((v) => ({ id: v.id || v.referenceId, name: v.name, referenceId: v.referenceId, custom: true }));
  const all = [...presets, ...custom];
  // Merge admin director metadata (fullName + prompt) onto each voice.
  return all.map((v) => {
    const p = profiles[v.id];
    if (!p) return v;
    return { ...v, fullName: p.fullName || v.fullName, prompt: p.prompt || v.prompt };
  });
}

export function resolveVoice(sysConfig, voiceId) {
  const voices = getAvailableVoices(sysConfig);
  return voices.find((v) => v.id === voiceId) || voices[0];
}

// Absolute Worker URL — works from both the Android WebView (origin
// https://localhost) and the web build (same origin), thanks to `Access-Control-Allow-Origin: *`.
export const VOICE_API = "https://nextext.nextext-app.workers.dev/api/generate-voice";
// Voice-conversion proxy: user records their own voice, we forward it (with the
// target reference_id) to Fish Audio and stream the converted audio back.
export const VOICE_CONVERT_API = "https://nextext.nextext-app.workers.dev/api/convert-voice";

const getNativeTTS = () => {
  try {
    return (typeof window !== "undefined" && window.Capacitor?.Plugins?.NextextNative) || null;
  } catch {
    return null;
  }
};
const isNativePlatform = () => !!(typeof window !== "undefined" && window.Capacitor?.isNativePlatform && window.Capacitor.isNativePlatform());

// Global "socket" for voice: AppSettings.global_voice_enabled (stored in the AI
// system config doc which acts as the app-wide settings object).
export const VOICE_SYSTEM_REF = ["config", "system"];

// Strip markdown/emphasis that a TTS engine would read aloud, and keep only
// recognized Fish Audio emotion brackets ([laughing], [serious], …) so the
// spoken output isn't polluted with asterisks, italics or stray brackets.
const FISH_EMOTIONS = new Set([
  "laughing", "laugh", "serious", "slow", "whispering", "whisper", "angry",
  "sad", "happy", "excited", "calm", "shouting", "surprised", "crying",
  "sigh", "gasp", "gasps", "cough", "sniff", "yawn", "clear throat", "pause",
  "long pause", "thinking", "sarcastic", "robotic", "nervous", "scared",
  "disgusted", "whispering",
]);
export function sanitizeForTTS(text) {
  if (!text) return "";
  let s = String(text);
  s = s.replace(/\*\*\*/g, "").replace(/\*\*/g, "").replace(/\*/g, "");
  s = s.replace(/__/g, "").replace(/_/g, "").replace(/`/g, "").replace(/~{1,2}/g, "");
  s = s.replace(/```[\s\S]*?```/g, "").replace(/```/g, "");
  s = s.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  s = s.replace(/\[([^\]]+)\]/g, (m, tag) => (FISH_EMOTIONS.has(String(tag).trim().toLowerCase()) ? m : ""));
  s = s.replace(/\s+/g, " ").replace(/\s+([.,!?;:])/g, "$1").trim();
  return s;
}

// Returns the global voice master switch (default true).
export async function getGlobalVoiceEnabled() {
  try {
    const snap = await getDoc(doc(db, ...VOICE_SYSTEM_REF));
    const data = snap.exists() ? snap.data() : {};
    return data.global_voice_enabled !== false;
  } catch {
    return true;
  }
}

// Sets the global voice master switch (default true when absent).
export async function setGlobalVoiceEnabled(enabled, adminUid) {
  await setDoc(doc(db, ...VOICE_SYSTEM_REF), {
    global_voice_enabled: !!enabled,
    updatedBy: adminUid || null,
    updatedAt: new Date(),
  }, { merge: true });
  return !!enabled;
}

// Per-user TTS (hear AI replies) + premium AI-access gating. Stored on the user
// document so it syncs across the user's own devices.
export function getVoiceUserDefaults() {
  return {
    user_tts_enabled: false,
    has_ai_access: false,
  };
}

// Toggle the user's "hear AI replies" flag. Returns the new value.
export async function setUserTtsEnabled(userUid, enabled) {
  if (!userUid) return false;
  await setDoc(doc(db, "users", userUid), { user_tts_enabled: !!enabled }, { merge: true });
  return !!enabled;
}

// Reads the user's voice-related flags from their users doc.
export async function getUserVoiceFlags(userUid) {
  try {
    const snap = await getDoc(doc(db, "users", userUid));
    const d = snap.exists() ? snap.data() : {};
    return {
      user_tts_enabled: d.user_tts_enabled === true,
      has_ai_access: d.has_ai_access === true,
    };
  } catch {
    return { user_tts_enabled: false, has_ai_access: false };
  }
}

// Evaluate whether we should synthesize & play a voice reply for this user.
export async function shouldPlayVoiceReply(userUid) {
  if (!userUid) return false;
  const [voiceEnabled, flags] = await Promise.all([getGlobalVoiceEnabled(), getUserVoiceFlags(userUid)]);
  return voiceEnabled === true && flags.user_tts_enabled === true;
}

// Admin Dashboard: persist the Fish Audio key in Firestore (separate doc from
// config/system so getSystemConfig never ships it to clients). The Worker reads
// this doc server-side.
export async function setFishAudioKey(key) {
  await setDoc(doc(db, "config", "fishAudioKey"), { key: String(key || "").trim() }, { merge: true });
}
export async function getFishAudioKey() {
  try {
    const snap = await getDoc(doc(db, "config", "fishAudioKey"));
    return snap.exists() ? (snap.data().key || "") : "";
  } catch {
    return "";
  }
}

// Core: turn text into raw MP3 bytes. Tries, in order:
//   1) Cloudflare Worker proxy (key server-side),
//   2) Native Android bridge (key compiled into the APK),
//   3) Direct Fish Audio call using the admin-configured key (client-readable
//      from config/fishAudioKey) — so podcasts/voice replies keep working even
//      if the Worker proxy's key is stale or lacks permission for a voice.
// `referenceId` selects the Fish Audio voice (defaults to Y Mizrachi).
async function fetchVoiceBytes(text, referenceId) {
  const clean = sanitizeForTTS(text);
  if (!clean) throw new Error("Nothing to speak.");
  const ref = referenceId || Y_MIZRACHI_VOICE_ID;

  // 1) Cloudflare Worker proxy — key stays server-side.
  let workerErr = null;
  try {
    const resp = await fetch(VOICE_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: clean, referenceId: ref, model: FISH_MODEL }),
    });
    if (resp.ok) return await resp.arrayBuffer();
    try { const j = await resp.json(); workerErr = j?.error || `Voice service error (${resp.status}).`; } catch { workerErr = `Voice service error (${resp.status}).`; }
  } catch (e) {
    workerErr = e?.message || "Voice worker unreachable.";
  }
  console.error("[tts] worker synthesis failed:", workerErr);

  // 2) Native Android bridge fallback — key is compiled into the APK.
  if (isNativePlatform()) {
    const native = getNativeTTS();
    if (native && typeof native.tts === "function") {
      try {
        const res = await native.tts({ text: clean, referenceId: ref, model: FISH_MODEL });
        const b64 = res?.base64;
        if (b64) {
          const bin = atob(b64);
          const bytes = new Uint8Array(bin.length);
          for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
          return bytes.buffer;
        }
      } catch (e2) {
        console.error("[tts] native synthesis failed:", e2?.message);
      }
    }
  }

  // 3) Direct Fish Audio call with the admin-configured key. This is the path
  // that fixes "Missing or insufficient permissions" when the Worker's key is
  // wrong/stale — the admin's own key (set in the dashboard) is used directly.
  try {
    const key = (await getFishAudioKey() || "").trim();
    if (key) {
      const resp = await fetch("https://api.fish.audio/v1/tts", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
        body: JSON.stringify({ text: clean, reference_id: ref, model: FISH_MODEL }),
      });
      if (resp.ok) return await resp.arrayBuffer();
      try { const j = await resp.json(); workerErr = j?.error || workerErr; } catch {}
    }
  } catch (e3) {
    console.error("[tts] direct fish synthesis failed:", e3?.message);
  }

  throw new Error(workerErr ? `Voice generation failed: ${workerErr}` : "Voice generation unavailable. The voice worker may not be deployed.");
}

// POST to Fish Audio (via Worker) and return a playable Blob URL of the MP3.
export async function synthesizeSpeech(text, referenceId) {
  const buf = await fetchVoiceBytes(text, referenceId);
  return URL.createObjectURL(new Blob([buf], { type: "audio/mpeg" }));
}

// Synthesize and fetch the raw MP3 as a Blob (for uploading a custom voice note).
export async function synthesizeSpeechBytes(text, referenceId) {
  const buf = await fetchVoiceBytes(text, referenceId);
  return new Blob([buf], { type: "audio/mpeg" });
}
