import { doc, getDoc, setDoc } from "firebase/firestore";
import { db } from "./config";

// ── Fish Audio TTS (Y Mizrachi voice) ──────────────────────────────────────
// Free tier: s2.1-pro-free. Returns raw MP3 bytes which we turn into a Blob URL.
//
// SECURITY: the Fish Audio API key is NEVER present in the frontend bundle.
// Voice is generated by the Cloudflare Worker route /api/generate-voice, which
// holds the key server-side (env var or Firestore config/fishAudioKey) and
// proxies to Fish Audio. On Android we additionally fall back to the native
// NextextNative.tts bridge (key compiled into the APK, not the JS bundle).

export const FISH_MODEL = "s2.1-pro-free";
export const Y_MIZRACHI_VOICE_ID = "9cc36d13d091468fa9c4cab838a6ecdf";

// Built-in Fish Audio voices. Admins can add more via the dashboard
// (stored as config/system.customVoices = [{ id, name, referenceId }]).
export const VOICE_PRESETS = [
  { id: "y-mizrachi", name: "Y Mizrachi", referenceId: "9cc36d13d091468fa9c4cab838a6ecdf" },
  { id: "rosh", name: "Rosh", referenceId: "afe83a515f954ba281f0631e8b414f56" },
  { id: "trump", name: "Trump", referenceId: "ee45da2963c047a6a07cd21fa3259ae0" },
  { id: "magnus", name: "Magnus", referenceId: "913b80e159c045bea5025943a44f7670" },
];

// All voices available to a user given the current system config (honours the
// admin "hide Rosh" switch and appends admin-created custom voices).
export function getAvailableVoices(sysConfig) {
  const presets = VOICE_PRESETS.filter((v) => !(sysConfig?.hideRoshVoice === true && v.id === "rosh"));
  const custom = (sysConfig?.customVoices || [])
    .filter((v) => v && v.id && v.name && v.referenceId)
    .map((v) => ({ id: v.id, name: v.name, referenceId: v.referenceId, custom: true }));
  return [...presets, ...custom];
}

export function resolveVoice(sysConfig, voiceId) {
  const voices = getAvailableVoices(sysConfig);
  return voices.find((v) => v.id === voiceId) || voices[0];
}

// Absolute Worker URL — works from both the Android WebView (origin
// https://localhost) and the web build (same origin), thanks to `Access-Control-Allow-Origin: *`.
export const VOICE_API = "https://nextext.nextext-app.workers.dev/api/generate-voice";

const getNativeTTS = () => {
  try {
    return (typeof window !== "undefined" && window.Capacitor?.Plugins?.NextextNative) || null;
  } catch {
    return null;
  }
};
const isNativePlatform = () => !!(typeof window !== "undefined" && window.Capacitor?.isNativePlatform && window.Capacitor.isNativePlatform());

// Global "socket" for voice: AppSettings.global_voice_enabled (stored in the AI
// system config doc which acts as the app-wide settings object).
export const VOICE_SYSTEM_REF = ["config", "system"];

// Returns the global voice master switch (default true).
export async function getGlobalVoiceEnabled() {
  try {
    const snap = await getDoc(doc(db, ...VOICE_SYSTEM_REF));
    const data = snap.exists() ? snap.data() : {};
    return data.global_voice_enabled !== false;
  } catch {
    return true;
  }
}

// Sets the global voice master switch (default true when absent).
export async function setGlobalVoiceEnabled(enabled, adminUid) {
  await setDoc(doc(db, ...VOICE_SYSTEM_REF), {
    global_voice_enabled: !!enabled,
    updatedBy: adminUid || null,
    updatedAt: new Date(),
  }, { merge: true });
  return !!enabled;
}

// Per-user TTS (hear AI replies) + premium AI-access gating. Stored on the user
// document so it syncs across the user's own devices.
export function getVoiceUserDefaults() {
  return {
    user_tts_enabled: false,
    has_ai_access: false,
  };
}

// Toggle the user's "hear AI replies" flag. Returns the new value.
export async function setUserTtsEnabled(userUid, enabled) {
  if (!userUid) return false;
  await setDoc(doc(db, "users", userUid), { user_tts_enabled: !!enabled }, { merge: true });
  return !!enabled;
}

// Reads the user's voice-related flags from their users doc.
export async function getUserVoiceFlags(userUid) {
  try {
    const snap = await getDoc(doc(db, "users", userUid));
    const d = snap.exists() ? snap.data() : {};
    return {
      user_tts_enabled: d.user_tts_enabled === true,
      has_ai_access: d.has_ai_access === true,
    };
  } catch {
    return { user_tts_enabled: false, has_ai_access: false };
  }
}

// Evaluate whether we should synthesize & play a voice reply for this user.
export async function shouldPlayVoiceReply(userUid) {
  if (!userUid) return false;
  const [voiceEnabled, flags] = await Promise.all([getGlobalVoiceEnabled(), getUserVoiceFlags(userUid)]);
  return voiceEnabled === true && flags.user_tts_enabled === true;
}

// Admin Dashboard: persist the Fish Audio key in Firestore (separate doc from
// config/system so getSystemConfig never ships it to clients). The Worker reads
// this doc server-side.
export async function setFishAudioKey(key) {
  await setDoc(doc(db, "config", "fishAudioKey"), { key: String(key || "").trim() }, { merge: true });
}
export async function getFishAudioKey() {
  try {
    const snap = await getDoc(doc(db, "config", "fishAudioKey"));
    return snap.exists() ? (snap.data().key || "") : "";
  } catch {
    return "";
  }
}

// Core: turn text into raw MP3 bytes via the Worker proxy (primary) or the
// native Android bridge (fallback). `referenceId` selects the Fish Audio voice
// (defaults to Y Mizrachi). Throws a readable error on failure.
async function fetchVoiceBytes(text, referenceId) {
  const clean = String(text || "").slice(0, 800).trim();
  if (!clean) throw new Error("Nothing to speak.");
  const ref = referenceId || Y_MIZRACHI_VOICE_ID;

  // 1) Cloudflare Worker proxy — key stays server-side.
  try {
    const resp = await fetch(VOICE_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: clean, referenceId: ref, model: FISH_MODEL }),
    });
    if (resp.ok) return await resp.arrayBuffer();
    let msg = `Voice service error (${resp.status}).`;
    try { const j = await resp.json(); if (j?.error) msg = j.error; } catch {}
    throw new Error(msg);
  } catch (e) {
    if (e.message && /Voice service/.test(e.message)) throw e;
    console.error("[tts] worker synthesis failed, trying native fallback:", e?.message);
  }

  // 2) Native Android bridge fallback — key is compiled into the APK.
  if (isNativePlatform()) {
    const native = getNativeTTS();
    if (native && typeof native.tts === "function") {
      try {
        const res = await native.tts({ text: clean, referenceId: ref, model: FISH_MODEL });
        const b64 = res?.base64;
        if (!b64) throw new Error("Voice service returned no audio.");
        const bin = atob(b64);
        const bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        return bytes.buffer;
      } catch (e2) {
        console.error("[tts] native synthesis failed:", e2?.message);
      }
    }
  }
  throw new Error("Voice generation unavailable. The voice worker may not be deployed.");
}

// POST to Fish Audio (via Worker) and return a playable Blob URL of the MP3.
export async function synthesizeSpeech(text, referenceId) {
  const buf = await fetchVoiceBytes(text, referenceId);
  return URL.createObjectURL(new Blob([buf], { type: "audio/mpeg" }));
}

// Synthesize and fetch the raw MP3 as a Blob (for uploading a custom voice note).
export async function synthesizeSpeechBytes(text, referenceId) {
  const buf = await fetchVoiceBytes(text, referenceId);
  return new Blob([buf], { type: "audio/mpeg" });
}
